manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: jatus93
      url-base: https://github.com/Jatus93
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-config
      remote: jatus93
      revision: lily58-wip
      path: zmk-config-module
  self:
    path: config
